In [41]:
# Gabriel Nilsson

# Function that returns new matrix with normalized columns
def normalize_cols(A):
    M = matrix.identity(QQ, A.ncols())
    for i in range(len(A.columns())):
        col_sum = sum(A[:,i])
        M[:,i] = vector(QQ, [val/col_sum for val in A[:,i]])
    return M

In [42]:
# Matrices collected during the data collection
A1 = matrix(RR, [[15,4,0,0,7],
                 [ 2,4,0,2,0],
                 [ 1,0,2,0,1],
                 [ 2,0,0,3,0],
                 [ 4,0,1,0,6]]).transpose()

A2 = matrix(RR, [[16,5,1,2,3],
                 [ 4,2,2,0,1],
                 [ 0,0,0,1,1],
                 [ 0,4,0,0,3],
                 [ 4,0,1,2,2]]).transpose()

A3 = matrix(RR, [[20,0,1,1,3],
                 [ 4,4,0,0,0],
                 [ 3,0,3,0,1],
                 [ 0,2,0,5,0],
                 [ 3,0,0,0,4]]).transpose()

#Average Matrix of the sample matrices
Av = A1+A2+A3/3

# Normalizing the columns of the Average Matrix
M = normalize_cols(Av)

#Printing The Average Matrix from the 3 data collections and the Markov Matrix
print(Av.n(digits=3), end='\n\n')
print(M.n(digits=3), end='\n\n')

[ 37.7  7.33  2.00  2.00  9.00]
[ 9.00  7.33 0.000  4.67 0.000]
[ 1.33  2.00  3.00 0.000  2.00]
[ 2.33  2.00  1.00  4.67  2.00]
[ 11.0  1.00  2.33  3.00  9.33]

[ 0.614  0.373  0.240  0.140  0.403]
[ 0.147  0.373  0.000  0.326  0.000]
[0.0217  0.102  0.360  0.000 0.0896]
[0.0380  0.102  0.120  0.326 0.0896]
[ 0.179 0.0508  0.280  0.209  0.418]



In [43]:
# Function to print the eigenvalues and eigenvectors of the Markov Matrix generated in the last code cell.
def print_eigenstuff(A):
    for eigenstuff in A.eigenvectors_right():
        print("Eigenvalue:", eigenstuff[0])
        print("Eigenvector:", eigenstuff[1][0])
    print()

# Calling the function to print the eigenvalues and eigenvectors of the Markov Matrix = M
print_eigenstuff(M)

Eigenvalue: 0.07533464611737358?
Eigenvector: (1, -0.8009677369377102?, 0.526515519458645?, 0.2813004233879371?, -1.006848205908872?)
Eigenvalue: 0.2731679858821693?
Eigenvector: (1, 0.733340438424527?, 0.5755575046302950?, -0.6752934291853325?, -1.633604513869490?)
Eigenvalue: 0.9999999999999999?
Eigenvector: (1, 0.337391771359244?, 0.155287573579407?, 0.199168443486095?, 0.483895094505368?)
Eigenvalue: 0.3710005009126502? - 0.01096360832109301?*I
Eigenvector: (1, 0.0466690551751003? + 0.3277912856041272?*I, -0.2783096658859392? + 0.01232485068220897?*I, -0.4399303367490370? - 0.00346515231725943?*I, -0.3284290525401242? - 0.3366509839690768?*I)
Eigenvalue: 0.3710005009126502? + 0.01096360832109301?*I
Eigenvector: (1, 0.0466690551751003? - 0.3277912856041272?*I, -0.2783096658859392? - 0.01232485068220897?*I, -0.4399303367490370? + 0.00346515231725943?*I, -0.3284290525401242? + 0.3366509839690768?*I)



In [52]:
# Function to calculate the Stationary Vector from the Markov Matrix
def stationary_vector(A):
    for eigenstuff in A.eigenvectors_right():
        if abs(eigenstuff[0] - 1) < .0001:
            return eigenstuff[1][0]

print("Stationary vector:", stationary_vector(M))


Stationary vector: (1, 0.337391771359244?, 0.155287573579407?, 0.199168443486095?, 0.483895094505368?)


In [51]:
import numpy as np

# Defining 3 different initial distributions
init_dist1 = vector([0.5,0.25,0.125,0.125,0])
init_dist2 = vector([0,0,1,0,0])
init_dist3 = vector([0.2,0.2,0.2,0.2,0.2])


initial_distributions = [init_dist1, init_dist2, init_dist3]

# Funtion to Potentialize M (Markov Matrix) to n with the 3 different initial distributions until the Stationary Vector calculated before is achieved.
def limit_pattern(M, init_dists):

    stat_vec = stationary_vector(M)
    # Turning the Stationary Vector into a probability distribution (Normalizing)
    norm_stat_vec = np.array(stat_vec)/sum(stat_vec)

    print(vector(RR, norm_stat_vec).n(digits=3))

    for dist in init_dists:
        old_dist = dist
        print(f"\n\nUsing distribution {dist.n(digits=3)}\n")
        for i in range(17):
            if i % 2 == 0:
                print(f"After {i} time-steps we have: {old_dist.n(digits=3)}")
            new_dist = M*old_dist
            old_dist = new_dist

    print('\n\n\n\n')
    
for M in [M]:
    limit_pattern(M, initial_distributions)

(0.460, 0.155, 0.0714, 0.0915, 0.222)


Using distribution (0.500, 0.250, 0.125, 0.125, 0.000)

After 0 time-steps we have: (0.500, 0.250, 0.125, 0.125, 0.000)
After 2 time-steps we have: (0.452, 0.176, 0.0747, 0.0951, 0.203)
After 4 time-steps we have: (0.458, 0.158, 0.0720, 0.0922, 0.220)
After 6 time-steps we have: (0.459, 0.155, 0.0715, 0.0917, 0.222)
After 8 time-steps we have: (0.460, 0.155, 0.0714, 0.0916, 0.222)
After 10 time-steps we have: (0.460, 0.155, 0.0714, 0.0915, 0.222)
After 12 time-steps we have: (0.460, 0.155, 0.0714, 0.0915, 0.222)
After 14 time-steps we have: (0.460, 0.155, 0.0714, 0.0915, 0.222)
After 16 time-steps we have: (0.460, 0.155, 0.0714, 0.0915, 0.222)


Using distribution (0.000, 0.000, 1.00, 0.000, 0.000)

After 0 time-steps we have: (0.000, 0.000, 1.00, 0.000, 0.000)
After 2 time-steps we have: (0.363, 0.0743, 0.160, 0.116, 0.286)
After 4 time-steps we have: (0.445, 0.140, 0.0798, 0.0969, 0.239)
After 6 time-steps we have: (0.458, 0.153, 0.0722, 0.0923