In [36]:
# Gabriel Nilsson
import numpy as np
A1 = matrix(RR, [[15,4,0,0,7],
             [2,4,0,2,0],
             [1,0,2,0,1],
             [2,0,0,3,0],
             [4,0,1,0,6]]).transpose()


print(A1, end='\n\n')
for i in range(len(A1.columns())):
    col_sum = sum(A1[:,i])
    A1[:,i] = vector(RR, [val/col_sum for val in A1[:,i]])
print(A1)





[ 15.0000000000000  2.00000000000000  1.00000000000000  2.00000000000000  4.00000000000000]
[ 4.00000000000000  4.00000000000000 0.000000000000000 0.000000000000000 0.000000000000000]
[0.000000000000000 0.000000000000000  2.00000000000000 0.000000000000000  1.00000000000000]
[0.000000000000000  2.00000000000000 0.000000000000000  3.00000000000000 0.000000000000000]
[ 7.00000000000000 0.000000000000000  1.00000000000000 0.000000000000000  6.00000000000000]

[ 0.576923076923077  0.250000000000000  0.250000000000000  0.400000000000000  0.363636363636364]
[ 0.153846153846154  0.500000000000000  0.000000000000000  0.000000000000000  0.000000000000000]
[ 0.000000000000000  0.000000000000000  0.500000000000000  0.000000000000000 0.0909090909090909]
[ 0.000000000000000  0.250000000000000  0.000000000000000  0.600000000000000  0.000000000000000]
[ 0.269230769230769  0.000000000000000  0.250000000000000  0.000000000000000  0.545454545454545]


[0 1]
[2 7]
