In [63]:
# Gabriel Nilsson

# Function that returns new matrix with normalized columns
def normalize_cols(A):
    M = matrix.identity(QQ, A.ncols())
    for i in range(len(A.columns())):
        col_sum = sum(A[:,i])
        M[:,i] = vector(QQ, [val/col_sum for val in A[:,i]])
    return M

In [64]:
# Matrices
A1 = matrix(RR, [[15,4,0,0,7],
                 [ 2,4,0,2,0],
                 [ 1,0,2,0,1],
                 [ 2,0,0,3,0],
                 [ 4,0,1,0,6]]).transpose()

A2 = matrix(RR, [[18,5,1,2,3],
                 [ 5,2,2,0,1],
                 [ 0,0,0,1,1],
                 [ 0,3,0,0,2],
                 [ 4,0,1,2,4]]).transpose()

A3 = matrix(RR, [[25,0,1,1,3],
                 [ 4,7,0,0,0],
                 [ 3,0,3,0,1],
                 [ 0,2,0,5,0],
                 [ 6,0,0,0,8]]).transpose()

# Normalizing the columns
M1 = normalize_cols(A1)
M2 = normalize_cols(A2)
M3 = normalize_cols(A3)
print(A1.n(digits=3), end='\n\n')
print(M1.n(digits=3), end='\n\n')
print(M2.n(digits=3), end='\n\n')
print(M3.n(digits=3), end='\n\n')

[ 15.0  2.00  1.00  2.00  4.00]
[ 4.00  4.00 0.000 0.000 0.000]
[0.000 0.000  2.00 0.000  1.00]
[0.000  2.00 0.000  3.00 0.000]
[ 7.00 0.000  1.00 0.000  6.00]

[ 0.577  0.250  0.250  0.400  0.364]
[ 0.154  0.500  0.000  0.000  0.000]
[ 0.000  0.000  0.500  0.000 0.0909]
[ 0.000  0.250  0.000  0.600  0.000]
[ 0.269  0.000  0.250  0.000  0.545]

[ 0.621  0.500  0.000  0.000  0.364]
[ 0.172  0.200  0.000  0.600  0.000]
[0.0345  0.200  0.000  0.000 0.0909]
[0.0690  0.000  0.500  0.000  0.182]
[ 0.103  0.100  0.500  0.400  0.364]

[ 0.833  0.364  0.429  0.000  0.429]
[ 0.000  0.636  0.000  0.286  0.000]
[0.0333  0.000  0.429  0.000  0.000]
[0.0333  0.000  0.000  0.714  0.000]
[ 0.100  0.000  0.143  0.000  0.571]



In [69]:
# Eigenstuff
def print_eigenstuff(A):
    for eigenstuff in A.eigenvectors_right():
        print("Eigenvalue:", eigenstuff[0])
        print("Eigenvector:", eigenstuff[1][0])
    print()

print_eigenstuff(M1)
print_eigenstuff(M2)
print_eigenstuff(M3)

Eigenvalue: 1
Eigenvector: (1, 4/13, 14/117, 5/26, 77/117)
Eigenvalue: 0.2455886844116765?
Eigenvector: (1, -0.6047142733820082?, 0.4569569198436216?, 0.4265624761290291?, -1.278805122590643?)
Eigenvalue: 0.6456742145790650?
Eigenvector: (1, 1.056097362808526?, -3.011315542984466?, 5.780599472489859?, -4.825381292313919?)
Eigenvalue: 0.4155573616934405? - 0.08379176264210806?*I
Eigenvector: (1, -0.9179992370209513? + 0.9109233879553076?*I, -0.6807154252716830? - 0.6510081455748124?*I, 0.5664595115205156? - 1.492038340218924?*I, 0.0322551507721187? + 1.232123097838429?*I)
Eigenvalue: 0.4155573616934405? + 0.08379176264210806?*I
Eigenvector: (1, -0.9179992370209513? - 0.9109233879553076?*I, -0.6807154252716830? + 0.6510081455748124?*I, 0.5664595115205156? + 1.492038340218924?*I, 0.0322551507721187? - 1.232123097838429?*I)

Eigenvalue: 1
Eigenvector: (1, 4250/10759, 1710/10759, 2575/10759, 5379/10759)
Eigenvalue: 0.1482135604392351?
Eigenvector: (1, 25.73945198766058?, 12.46055103553837?,

In [70]:
# Stationary vector

def stationary_vector(A):
    for eigenstuff in A.eigenvectors_right():
        if eigenstuff[0] == 1:
            return eigenstuff[1][0]

print("Stationary vector:", stationary_vector(M1))
print("Stationary vector:", stationary_vector(M2))
print("Stationary vector:", stationary_vector(M3))


Stationary vector: (1, 4/13, 14/117, 5/26, 77/117)
Stationary vector: (1, 4250/10759, 1710/10759, 2575/10759, 5379/10759)
Stationary vector: (1, 11/120, 7/120, 7/60, 91/360)


In [91]:
init_dist1 = vector([0.5,0.25,0.125,0.125,0])
init_dist2 = vector([0,0,1,0,0])
init_dist3 = vector([0.2,0.2,0.2,0.2,0.2])


initial_distributions = [init_dist1, init_dist2, init_dist3]


def limit_pattern(M, init_dists):

    stat_vec = stationary_vector(M)
    norm_stat_vec = np.array(stat_vec)/sum(stat_vec)

    print(vector(RR, norm_stat_vec).n(digits=3))

    for dist in init_dists:
        old_dist = dist
        print(f"\n\nUsing distribution {dist.n(digits=3)}\n")
        for i in range(17):
            if i % 2 == 0:
                print(f"After {i} time-steps we have: {old_dist.n(digits=3)}")
            new_dist = M*old_dist
            old_dist = new_dist

    print('\n\n\n\n')
    
for M in [M1,M2,M3]:
    limit_pattern(M, initial_distributions)

(0.439, 0.135, 0.0525, 0.0844, 0.289)


Using distribution (0.500, 0.250, 0.125, 0.125, 0.000)

After 0 time-steps we have: (0.500, 0.250, 0.125, 0.125, 0.000)
After 2 time-steps we have: (0.431, 0.167, 0.0463, 0.133, 0.222)
After 4 time-steps we have: (0.439, 0.142, 0.0443, 0.110, 0.264)
After 6 time-steps we have: (0.440, 0.137, 0.0479, 0.0957, 0.279)
After 8 time-steps we have: (0.440, 0.136, 0.0504, 0.0891, 0.285)
After 10 time-steps we have: (0.439, 0.135, 0.0516, 0.0863, 0.287)
After 12 time-steps we have: (0.439, 0.135, 0.0521, 0.0852, 0.288)
After 14 time-steps we have: (0.439, 0.135, 0.0524, 0.0847, 0.289)
After 16 time-steps we have: (0.439, 0.135, 0.0525, 0.0846, 0.289)


Using distribution (0.000, 0.000, 1.00, 0.000, 0.000)

After 0 time-steps we have: (0.000, 0.000, 1.00, 0.000, 0.000)
After 2 time-steps we have: (0.360, 0.0385, 0.273, 0.000, 0.329)
After 4 time-steps we have: (0.423, 0.0996, 0.114, 0.0244, 0.339)
After 6 time-steps we have: (0.434, 0.124, 0.0737, 0.0525, 